language: go

go:
  - master # This uses automatically the latest version of go

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.tar.gz
  - tar -xzvf hugo_extended_0.68.3_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version

script:
  - hugo # This commands builds your website on travis

deploy:
  local_dir:  # Default static site output dir for Hugo
  repo: cloudback/cloudback.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  edge: true
  keep_history: true
  cleanup: false
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  on:
    branch: master
